	drop table dev.dev_temp_msj_risk_jdata_feature_train_v3_${suffix};
    create table if not exists dev.dev_temp_msj_risk_jdata_feature_train_v3_${suffix} stored as orc as
    select
            a.*,
			b.`(user_id)?+.+`,
			c.`(sku_id)?+.+`,
			d.`(action_brand)?+.+`,
			e.`(user_id|action_brand)?+.+`,
			
			user_sku_month_browse_cnt     /  user_month_browse_cnt       as user_usersku2user_month_browse_rate,   
			user_sku_month_add_cart_cnt	  /  user_month_add_cart_cnt	 as user_usersku2user_month_add_cart_rate,
			user_sku_month_del_cart_cnt	  /  user_month_del_cart_cnt	 as user_usersku2user_month_del_cart_rate,
			user_sku_month_order_cnt	  /  user_month_order_cnt	     as user_usersku2user_month_order_rate,	 
			user_sku_month_focus_cnt	  /  user_month_focus_cnt	     as user_usersku2user_month_focus_rate,	 
			user_sku_month_click_cnt	  /  user_month_click_cnt	     as user_usersku2user_month_click_rate,	 
			user_sku_15days_browse_cnt    /  user_15days_browse_cnt      as user_usersku2user_15days_browse_rate,  
			user_sku_15days_add_cart_cnt  /  user_15days_add_cart_cnt    as user_usersku2user_15days_add_cart_rate,
			user_sku_15days_del_cart_cnt  /  user_15days_del_cart_cnt    as user_usersku2user_15days_del_cart_rate,
			user_sku_15days_order_cnt	  /  user_15days_order_cnt	     as user_usersku2user_15days_order_rate,	 
			user_sku_15days_focus_cnt	  /  user_15days_focus_cnt	     as user_usersku2user_15days_focus_rate,	 
			user_sku_15days_click_cnt	  /  user_15days_click_cnt	     as user_usersku2user_15days_click_rate,	 
			user_sku_10days_browse_cnt    /  user_10days_browse_cnt      as user_usersku2user_10days_browse_rate,  
			user_sku_10days_add_cart_cnt  /  user_10days_add_cart_cnt    as user_usersku2user_10days_add_cart_rate,
			user_sku_10days_del_cart_cnt  /  user_10days_del_cart_cnt    as user_usersku2user_10days_del_cart_rate,
			user_sku_10days_order_cnt	  /  user_10days_order_cnt	     as user_usersku2user_10days_order_rate,	 
			user_sku_10days_focus_cnt	  /  user_10days_focus_cnt	     as user_usersku2user_10days_focus_rate,	 
			user_sku_10days_click_cnt	  /  user_10days_click_cnt	     as user_usersku2user_10days_click_rate,	 
			user_sku_7days_browse_cnt     /  user_7days_browse_cnt       as user_usersku2user_7days_browse_rate,   
			user_sku_7days_add_cart_cnt	  /  user_7days_add_cart_cnt	 as user_usersku2user_7days_add_cart_rate,
			user_sku_7days_del_cart_cnt	  /  user_7days_del_cart_cnt	 as user_usersku2user_7days_del_cart_rate,
			user_sku_7days_order_cnt	  /  user_7days_order_cnt	     as user_usersku2user_7days_order_rate,	 
			user_sku_7days_focus_cnt	  /  user_7days_focus_cnt	     as user_usersku2user_7days_focus_rate,	 
			user_sku_7days_click_cnt	  /  user_7days_click_cnt	     as user_usersku2user_7days_click_rate,	 
			
			user_sku_5days_browse_cnt     /  user_5days_browse_cnt       as user_usersku2user_5days_browse_rate,   
			user_sku_5days_add_cart_cnt	  /  user_5days_add_cart_cnt	 as user_usersku2user_5days_add_cart_rate,
			user_sku_5days_del_cart_cnt	  /  user_5days_del_cart_cnt	 as user_usersku2user_5days_del_cart_rate,
			user_sku_5days_order_cnt	  /  user_5days_order_cnt	     as user_usersku2user_5days_order_rate,	 
			user_sku_5days_focus_cnt	  /  user_5days_focus_cnt	     as user_usersku2user_5days_focus_rate,	 
			user_sku_5days_click_cnt	  /  user_5days_click_cnt	     as user_usersku2user_5days_click_rate,	 
			
			user_sku_3days_browse_cnt     /  user_3days_browse_cnt       as user_usersku2user_3days_browse_rate,   
			user_sku_3days_add_cart_cnt	  /  user_3days_add_cart_cnt	 as user_usersku2user_3days_add_cart_rate,
			user_sku_3days_del_cart_cnt	  /  user_3days_del_cart_cnt	 as user_usersku2user_3days_del_cart_rate,
			user_sku_3days_order_cnt	  /  user_3days_order_cnt	     as user_usersku2user_3days_order_rate,	 
			user_sku_3days_focus_cnt	  /  user_3days_focus_cnt	     as user_usersku2user_3days_focus_rate,	 
			user_sku_3days_click_cnt	  /  user_3days_click_cnt	     as user_usersku2user_3days_click_rate,	 
			
			user_sku_month_browse_cnt     /  sku_month_browse_cnt       as user_usersku2sku_month_browse_rate,   
			user_sku_month_add_cart_cnt	  /  sku_month_add_cart_cnt	    as user_usersku2sku_month_add_cart_rate,
			user_sku_month_del_cart_cnt	  /  sku_month_del_cart_cnt	    as user_usersku2sku_month_del_cart_rate,
			user_sku_month_order_cnt	  /  sku_month_order_cnt	    as user_usersku2sku_month_order_rate,	 
			user_sku_month_focus_cnt	  /  sku_month_focus_cnt	    as user_usersku2sku_month_focus_rate,	 
			user_sku_month_click_cnt	  /  sku_month_click_cnt	    as user_usersku2sku_month_click_rate,	 
			user_sku_15days_browse_cnt    /  sku_15days_browse_cnt      as user_usersku2sku_15days_browse_rate,  
			user_sku_15days_add_cart_cnt  /  sku_15days_add_cart_cnt    as user_usersku2sku_15days_add_cart_rate,
			user_sku_15days_del_cart_cnt  /  sku_15days_del_cart_cnt    as user_usersku2sku_15days_del_cart_rate,
			user_sku_15days_order_cnt	  /  sku_15days_order_cnt	    as user_usersku2sku_15days_order_rate,	 
			user_sku_15days_focus_cnt	  /  sku_15days_focus_cnt	    as user_usersku2sku_15days_focus_rate,	 
			user_sku_15days_click_cnt	  /  sku_15days_click_cnt	    as user_usersku2sku_15days_click_rate,	 
			user_sku_10days_browse_cnt    /  sku_10days_browse_cnt      as user_usersku2sku_10days_browse_rate,  
			user_sku_10days_add_cart_cnt  /  sku_10days_add_cart_cnt    as user_usersku2sku_10days_add_cart_rate,
			user_sku_10days_del_cart_cnt  /  sku_10days_del_cart_cnt    as user_usersku2sku_10days_del_cart_rate,
			user_sku_10days_order_cnt	  /  sku_10days_order_cnt	    as user_usersku2sku_10days_order_rate,	 
			user_sku_10days_focus_cnt	  /  sku_10days_focus_cnt	    as user_usersku2sku_10days_focus_rate,	 
			user_sku_10days_click_cnt	  /  sku_10days_click_cnt	    as user_usersku2sku_10days_click_rate,	 
			user_sku_7days_browse_cnt     /  sku_7days_browse_cnt       as user_usersku2sku_7days_browse_rate,   
			user_sku_7days_add_cart_cnt	  /  sku_7days_add_cart_cnt	 	as user_usersku2sku_7days_add_cart_rate,
			user_sku_7days_del_cart_cnt	  /  sku_7days_del_cart_cnt	 	as user_usersku2sku_7days_del_cart_rate,
			user_sku_7days_order_cnt	  /  sku_7days_order_cnt	    as user_usersku2sku_7days_order_rate,	 
			user_sku_7days_focus_cnt	  /  sku_7days_focus_cnt	    as user_usersku2sku_7days_focus_rate,	 
			user_sku_7days_click_cnt	  /  sku_7days_click_cnt	    as user_usersku2sku_7days_click_rate,
			
			user_sku_5days_browse_cnt     /  sku_5days_browse_cnt       as user_usersku2sku_5days_browse_rate,   
			user_sku_5days_add_cart_cnt	  /  sku_5days_add_cart_cnt	 	as user_usersku2sku_5days_add_cart_rate,
			user_sku_5days_del_cart_cnt	  /  sku_5days_del_cart_cnt	 	as user_usersku2sku_5days_del_cart_rate,
			user_sku_5days_order_cnt	  /  sku_5days_order_cnt	    as user_usersku2sku_5days_order_rate,	 
			user_sku_5days_focus_cnt	  /  sku_5days_focus_cnt	    as user_usersku2sku_5days_focus_rate,	 
			user_sku_5days_click_cnt	  /  sku_5days_click_cnt	    as user_usersku2sku_5days_click_rate,
			
			user_sku_3days_browse_cnt     /  sku_3days_browse_cnt       as user_usersku2sku_3days_browse_rate,   
			user_sku_3days_add_cart_cnt	  /  sku_3days_add_cart_cnt	    as user_usersku2sku_3days_add_cart_rate,
			user_sku_3days_del_cart_cnt	  /  sku_3days_del_cart_cnt	    as user_usersku2sku_3days_del_cart_rate,
			user_sku_3days_order_cnt	  /  sku_3days_order_cnt	    as user_usersku2sku_3days_order_rate,	 
			user_sku_3days_focus_cnt	  /  sku_3days_focus_cnt	    as user_usersku2sku_3days_focus_rate,	 
			user_sku_3days_click_cnt	  /  sku_3days_click_cnt	    as user_usersku2sku_3days_click_rate,	 
			
			user_month_browse_cnt     /  sku_month_browse_cnt        as user_user2sku_month_browse_rate,   
			user_month_add_cart_cnt	  /  sku_month_add_cart_cnt	     as user_user2sku_month_add_cart_rate,
			user_month_del_cart_cnt	  /  sku_month_del_cart_cnt	     as user_user2sku_month_del_cart_rate,
			user_month_order_cnt	  /  sku_month_order_cnt	     as user_user2sku_month_order_rate,	 
			user_month_focus_cnt	  /  sku_month_focus_cnt	     as user_user2sku_month_focus_rate,	 
			user_month_click_cnt	  /  sku_month_click_cnt	     as user_user2sku_month_click_rate,	 
			user_15days_browse_cnt    /  sku_15days_browse_cnt       as user_user2sku_15days_browse_rate,  
			user_15days_add_cart_cnt  /  sku_15days_add_cart_cnt     as user_user2sku_15days_add_cart_rate,
			user_15days_del_cart_cnt  /  sku_15days_del_cart_cnt     as user_user2sku_15days_del_cart_rate,
			user_15days_order_cnt	  /  sku_15days_order_cnt	     as user_user2sku_15days_order_rate,	 
			user_15days_focus_cnt	  /  sku_15days_focus_cnt	     as user_user2sku_15days_focus_rate,	 
			user_15days_click_cnt	  /  sku_15days_click_cnt	     as user_user2sku_15days_click_rate,	 
			user_10days_browse_cnt    /  sku_10days_browse_cnt       as user_user2sku_10days_browse_rate,  
			user_10days_add_cart_cnt  /  sku_10days_add_cart_cnt     as user_user2sku_10days_add_cart_rate,
			user_10days_del_cart_cnt  /  sku_10days_del_cart_cnt     as user_user2sku_10days_del_cart_rate,
			user_10days_order_cnt	  /  sku_10days_order_cnt	     as user_user2sku_10days_order_rate,	 
			user_10days_focus_cnt	  /  sku_10days_focus_cnt	     as user_user2sku_10days_focus_rate,	 
			user_10days_click_cnt	  /  sku_10days_click_cnt	     as user_user2sku_10days_click_rate,	 
			user_7days_browse_cnt     /  sku_7days_browse_cnt        as user_user2sku_7days_browse_rate,   
			user_7days_add_cart_cnt	  /  sku_7days_add_cart_cnt	     as user_user2sku_7days_add_cart_rate,
			user_7days_del_cart_cnt	  /  sku_7days_del_cart_cnt	     as user_user2sku_7days_del_cart_rate,
			user_7days_order_cnt	  /  sku_7days_order_cnt	     as user_user2sku_7days_order_rate,	 
			user_7days_focus_cnt	  /  sku_7days_focus_cnt	     as user_user2sku_7days_focus_rate,	 
			user_7days_click_cnt	  /  sku_7days_click_cnt	     as user_user2sku_7days_click_rate,	
			
			user_5days_browse_cnt     /  sku_5days_browse_cnt        as user_user2sku_5days_browse_rate,   
			user_5days_add_cart_cnt	  /  sku_5days_add_cart_cnt	     as user_user2sku_5days_add_cart_rate,
			user_5days_del_cart_cnt	  /  sku_5days_del_cart_cnt	     as user_user2sku_5days_del_cart_rate,
			user_5days_order_cnt	  /  sku_5days_order_cnt	     as user_user2sku_5days_order_rate,	 
			user_5days_focus_cnt	  /  sku_5days_focus_cnt	     as user_user2sku_5days_focus_rate,	 
			user_5days_click_cnt	  /  sku_5days_click_cnt	     as user_user2sku_5days_click_rate,	

			user_3days_browse_cnt     /  sku_3days_browse_cnt        as user_user2sku_3days_browse_rate,   
			user_3days_add_cart_cnt	  /  sku_3days_add_cart_cnt	     as user_user2sku_3days_add_cart_rate,
			user_3days_del_cart_cnt	  /  sku_3days_del_cart_cnt	     as user_user2sku_3days_del_cart_rate,
			user_3days_order_cnt	  /  sku_3days_order_cnt	     as user_user2sku_3days_order_rate,	 
			user_3days_focus_cnt	  /  sku_3days_focus_cnt	     as user_user2sku_3days_focus_rate,	 
			user_3days_click_cnt	  /  sku_3days_click_cnt	     as user_user2sku_3days_click_rate,	
			
			
			(user_sku_month_browse_cnt    - user_month_sku_avg_browse_cnt) /  user_month_sku_avg_browse_cnt       	 as user_usersku2user_normalize_month_browse_rate,   
			(user_sku_month_add_cart_cnt  - user_month_sku_avg_add_cart_cnt) /  user_month_sku_avg_add_cart_cnt	     as user_usersku2user_normalize_month_add_cart_rate,
			(user_sku_month_del_cart_cnt  - user_month_sku_avg_del_cart_cnt) /  user_month_sku_avg_del_cart_cnt	     as user_usersku2user_normalize_month_del_cart_rate,
			(user_sku_month_order_cnt	  - user_month_sku_avg_order_cnt) /  user_month_sku_avg_order_cnt	         as user_usersku2user_normalize_month_order_rate,	 
			(user_sku_month_focus_cnt	  - user_month_sku_avg_focus_cnt) /  user_month_sku_avg_focus_cnt	         as user_usersku2user_normalize_month_focus_rate,	 
			(user_sku_month_click_cnt	  - user_month_sku_avg_click_cnt) /  user_month_sku_avg_click_cnt	         as user_usersku2user_normalize_month_click_rate,	 
			(user_sku_15days_browse_cnt   - user_15days_sku_avg_browse_cnt) /  user_15days_sku_avg_browse_cnt        as user_usersku2user_normalize_15days_browse_rate,  
			(user_sku_15days_add_cart_cnt - user_15days_sku_avg_add_cart_cnt) /  user_15days_sku_avg_add_cart_cnt    as user_usersku2user_normalize_15days_add_cart_rate,
			(user_sku_15days_del_cart_cnt - user_15days_sku_avg_del_cart_cnt) /  user_15days_sku_avg_del_cart_cnt    as user_usersku2user_normalize_15days_del_cart_rate,
			(user_sku_15days_order_cnt	 - user_15days_sku_avg_order_cnt) /  user_15days_sku_avg_order_cnt	         as user_usersku2user_normalize_15days_order_rate,	 
			(user_sku_15days_focus_cnt	 - user_15days_sku_avg_focus_cnt) /  user_15days_sku_avg_focus_cnt	         as user_usersku2user_normalize_15days_focus_rate,	 
			(user_sku_15days_click_cnt	 - user_15days_sku_avg_click_cnt) /  user_15days_sku_avg_click_cnt	         as user_usersku2user_normalize_15days_click_rate,	 
			(user_sku_10days_browse_cnt   - user_10days_sku_avg_browse_cnt) /  user_10days_sku_avg_browse_cnt        as user_usersku2user_normalize_10days_browse_rate,  
			(user_sku_10days_add_cart_cnt - user_10days_sku_avg_add_cart_cnt) /  user_10days_sku_avg_add_cart_cnt    as user_usersku2user_normalize_10days_add_cart_rate,
			(user_sku_10days_del_cart_cnt - user_10days_sku_avg_del_cart_cnt) /  user_10days_sku_avg_del_cart_cnt    as user_usersku2user_normalize_10days_del_cart_rate,
			(user_sku_10days_order_cnt	 - user_10days_sku_avg_order_cnt) /  user_10days_sku_avg_order_cnt	         as user_usersku2user_normalize_10days_order_rate,	 
			(user_sku_10days_focus_cnt	 - user_10days_sku_avg_focus_cnt) /  user_10days_sku_avg_focus_cnt	         as user_usersku2user_normalize_10days_focus_rate,	 
			(user_sku_10days_click_cnt	 - user_10days_sku_avg_click_cnt) /  user_10days_sku_avg_click_cnt	         as user_usersku2user_normalize_10days_click_rate,	 
			(user_sku_7days_browse_cnt    - user_7days_sku_avg_browse_cnt) /  user_7days_sku_avg_browse_cnt          as user_usersku2user_normalize_7days_browse_rate,   
			(user_sku_7days_add_cart_cnt	 - user_7days_sku_avg_add_cart_cnt) /  user_7days_sku_avg_add_cart_cnt	 as user_usersku2user_normalize_7days_add_cart_rate,
			(user_sku_7days_del_cart_cnt	 - user_7days_sku_avg_del_cart_cnt) /  user_7days_sku_avg_del_cart_cnt	 as user_usersku2user_normalize_7days_del_cart_rate,
			(user_sku_7days_order_cnt	 - user_7days_sku_avg_order_cnt) /  user_7days_sku_avg_order_cnt	         as user_usersku2user_normalize_7days_order_rate,	 
			(user_sku_7days_focus_cnt	 - user_7days_sku_avg_focus_cnt) /  user_7days_sku_avg_focus_cnt	         as user_usersku2user_normalize_7days_focus_rate,	 
			(user_sku_7days_click_cnt	 - user_7days_sku_avg_click_cnt) /  user_7days_sku_avg_click_cnt	         as user_usersku2user_normalize_7days_click_rate,	 
			
			(user_sku_5days_browse_cnt   - user_5days_sku_avg_browse_cnt) /  user_5days_sku_avg_browse_cnt           as user_usersku2user_normalize_5days_browse_rate,   
			(user_sku_5days_add_cart_cnt - user_5days_sku_avg_add_cart_cnt) /  user_5days_sku_avg_add_cart_cnt	     as user_usersku2user_normalize_5days_add_cart_rate,
			(user_sku_5days_del_cart_cnt - user_5days_sku_avg_del_cart_cnt) /  user_5days_sku_avg_del_cart_cnt	     as user_usersku2user_normalize_5days_del_cart_rate,
			(user_sku_5days_order_cnt	 - user_5days_sku_avg_order_cnt) /  user_5days_sku_avg_order_cnt	         as user_usersku2user_normalize_5days_order_rate,	 
			(user_sku_5days_focus_cnt	 - user_5days_sku_avg_focus_cnt) /  user_5days_sku_avg_focus_cnt	         as user_usersku2user_normalize_5days_focus_rate,	 
			(user_sku_5days_click_cnt	 - user_5days_sku_avg_click_cnt) /  user_5days_sku_avg_click_cnt	         as user_usersku2user_normalize_5days_click_rate,	 
			
			(user_sku_3days_browse_cnt    - user_3days_sku_avg_browse_cnt) /  user_3days_sku_avg_browse_cnt          as user_usersku2user_normalize_3days_browse_rate,   
			(user_sku_3days_add_cart_cnt	 - user_3days_sku_avg_add_cart_cnt) /  user_3days_sku_avg_add_cart_cnt	 as user_usersku2user_normalize_3days_add_cart_rate,
			(user_sku_3days_del_cart_cnt	 - user_3days_sku_avg_del_cart_cnt) /  user_3days_sku_avg_del_cart_cnt	 as user_usersku2user_normalize_3days_del_cart_rate,
			(user_sku_3days_order_cnt	 - user_3days_sku_avg_order_cnt) /  user_3days_sku_avg_order_cnt	         as user_usersku2user_normalize_3days_order_rate,	 
			(user_sku_3days_focus_cnt	 - user_3days_sku_avg_focus_cnt) /  user_3days_sku_avg_focus_cnt	         as user_usersku2user_normalize_3days_focus_rate,	 
			(user_sku_3days_click_cnt	 - user_3days_sku_avg_click_cnt) /  user_3days_sku_avg_click_cnt	         as user_usersku2user_normalize_3days_click_rate,
			
			(user_brand_month_browse_cnt    - user_month_brand_avg_browse_cnt) /  user_month_brand_avg_browse_cnt        as user_userbrand2user_normalize_month_browse_rate,   
			(user_brand_month_add_cart_cnt	 - user_month_brand_avg_add_cart_cnt) /  user_month_brand_avg_add_cart_cnt	 as user_userbrand2user_normalize_month_add_cart_rate,
			(user_brand_month_del_cart_cnt	 - user_month_brand_avg_del_cart_cnt) /  user_month_brand_avg_del_cart_cnt	 as user_userbrand2user_normalize_month_del_cart_rate,
			(user_brand_month_order_cnt	 - user_month_brand_avg_order_cnt) /  user_month_brand_avg_order_cnt	         as user_userbrand2user_normalize_month_order_rate,	 
			(user_brand_month_focus_cnt	 - user_month_brand_avg_focus_cnt) /  user_month_brand_avg_focus_cnt	         as user_userbrand2user_normalize_month_focus_rate,	 
			(user_brand_month_click_cnt	 - user_month_brand_avg_click_cnt) /  user_month_brand_avg_click_cnt	         as user_userbrand2user_normalize_month_click_rate,	 
			(user_brand_15days_browse_cnt   - user_15days_brand_avg_browse_cnt) /  user_15days_brand_avg_browse_cnt      as user_userbrand2user_normalize_15days_browse_rate,  
			(user_brand_15days_add_cart_cnt - user_15days_brand_avg_add_cart_cnt) /  user_15days_brand_avg_add_cart_cnt  as user_userbrand2user_normalize_15days_add_cart_rate,
			(user_brand_15days_del_cart_cnt - user_15days_brand_avg_del_cart_cnt) /  user_15days_brand_avg_del_cart_cnt  as user_userbrand2user_normalize_15days_del_cart_rate,
			(user_brand_15days_order_cnt	 - user_15days_brand_avg_order_cnt) /  user_15days_brand_avg_order_cnt	     as user_userbrand2user_normalize_15days_order_rate,	 
			(user_brand_15days_focus_cnt	 - user_15days_brand_avg_focus_cnt) /  user_15days_brand_avg_focus_cnt	     as user_userbrand2user_normalize_15days_focus_rate,	 
			(user_brand_15days_click_cnt	 - user_15days_brand_avg_click_cnt) /  user_15days_brand_avg_click_cnt	     as user_userbrand2user_normalize_15days_click_rate,	 
			(user_brand_10days_browse_cnt   - user_10days_brand_avg_browse_cnt) /  user_10days_brand_avg_browse_cnt      as user_userbrand2user_normalize_10days_browse_rate,  
			(user_brand_10days_add_cart_cnt - user_10days_brand_avg_add_cart_cnt) /  user_10days_brand_avg_add_cart_cnt  as user_userbrand2user_normalize_10days_add_cart_rate,
			(user_brand_10days_del_cart_cnt - user_10days_brand_avg_del_cart_cnt) /  user_10days_brand_avg_del_cart_cnt  as user_userbrand2user_normalize_10days_del_cart_rate,
			(user_brand_10days_order_cnt	 - user_10days_brand_avg_order_cnt) /  user_10days_brand_avg_order_cnt	     as user_userbrand2user_normalize_10days_order_rate,	 
			(user_brand_10days_focus_cnt	 - user_10days_brand_avg_focus_cnt) /  user_10days_brand_avg_focus_cnt	     as user_userbrand2user_normalize_10days_focus_rate,	 
			(user_brand_10days_click_cnt	 - user_10days_brand_avg_click_cnt) /  user_10days_brand_avg_click_cnt	     as user_userbrand2user_normalize_10days_click_rate,	 
			(user_brand_7days_browse_cnt    - user_7days_brand_avg_browse_cnt) /  user_7days_brand_avg_browse_cnt        as user_userbrand2user_normalize_7days_browse_rate,   
			(user_brand_7days_add_cart_cnt	 - user_7days_brand_avg_add_cart_cnt) /  user_7days_brand_avg_add_cart_cnt	 as user_userbrand2user_normalize_7days_add_cart_rate,
			(user_brand_7days_del_cart_cnt	 - user_7days_brand_avg_del_cart_cnt) /  user_7days_brand_avg_del_cart_cnt	 as user_userbrand2user_normalize_7days_del_cart_rate,
			(user_brand_7days_order_cnt	 - user_7days_brand_avg_order_cnt) /  user_7days_brand_avg_order_cnt	         as user_userbrand2user_normalize_7days_order_rate,	 
			(user_brand_7days_focus_cnt	 - user_7days_brand_avg_focus_cnt) /  user_7days_brand_avg_focus_cnt	         as user_userbrand2user_normalize_7days_focus_rate,	 
			(user_brand_7days_click_cnt	 - user_7days_brand_avg_click_cnt) /  user_7days_brand_avg_click_cnt	         as user_userbrand2user_normalize_7days_click_rate,	 
			
			(user_brand_5days_browse_cnt  - user_5days_brand_avg_browse_cnt) /  user_5days_brand_avg_browse_cnt          as user_userbrand2user_normalize_5days_browse_rate,   
			(user_brand_5days_add_cart_cnt- user_5days_brand_avg_add_cart_cnt) /user_5days_brand_avg_add_cart_cnt	     as user_userbrand2user_normalize_5days_add_cart_rate,
			(user_brand_5days_del_cart_cnt- user_5days_brand_avg_del_cart_cnt) /user_5days_brand_avg_del_cart_cnt	     as user_userbrand2user_normalize_5days_del_cart_rate,
			(user_brand_5days_order_cnt	 - user_5days_brand_avg_order_cnt) /  user_5days_brand_avg_order_cnt	         as user_userbrand2user_normalize_5days_order_rate,	 
			(user_brand_5days_focus_cnt	 - user_5days_brand_avg_focus_cnt) /  user_5days_brand_avg_focus_cnt	         as user_userbrand2user_normalize_5days_focus_rate,	 
			(user_brand_5days_click_cnt	 - user_5days_brand_avg_click_cnt) /  user_5days_brand_avg_click_cnt	         as user_userbrand2user_normalize_5days_click_rate,	 
			
			(user_brand_3days_browse_cnt    - user_3days_brand_avg_browse_cnt) /  user_3days_brand_avg_browse_cnt        as user_userbrand2user_normalize_3days_browse_rate,   
			(user_brand_3days_add_cart_cnt	 - user_3days_brand_avg_add_cart_cnt) /  user_3days_brand_avg_add_cart_cnt	 as user_userbrand2user_normalize_3days_add_cart_rate,
			(user_brand_3days_del_cart_cnt	 - user_3days_brand_avg_del_cart_cnt) /  user_3days_brand_avg_del_cart_cnt	 as user_userbrand2user_normalize_3days_del_cart_rate,
			(user_brand_3days_order_cnt	 - user_3days_brand_avg_order_cnt) /  user_3days_brand_avg_order_cnt	         as user_userbrand2user_normalize_3days_order_rate,	 
			(user_brand_3days_focus_cnt	 - user_3days_brand_avg_focus_cnt) /  user_3days_brand_avg_focus_cnt	         as user_userbrand2user_normalize_3days_focus_rate,	 
			(user_brand_3days_click_cnt	 - user_3days_brand_avg_click_cnt) /  user_3days_brand_avg_click_cnt	         as user_userbrand2user_normalize_3days_click_rate
    from
            (
                    select *,
					user_sku_month_browse_cnt   /user_sku_month_browse_day_cnt      as user_sku_month_day_avg_browse_cnt  ,
					user_sku_month_add_cart_cnt	/user_sku_month_add_cart_day_cnt	as user_sku_month_day_avg_add_cart_cnt,		
					user_sku_month_del_cart_cnt	/user_sku_month_del_cart_day_cnt	as user_sku_month_day_avg_del_cart_cnt,		
					user_sku_month_order_cnt	/user_sku_month_order_day_cnt		as user_sku_month_day_avg_order_cnt	  ,
					user_sku_month_focus_cnt	/user_sku_month_focus_day_cnt		as user_sku_month_day_avg_focus_cnt	  ,
					user_sku_month_click_cnt	/user_sku_month_click_day_cnt       as user_sku_month_day_avg_click_cnt,
					
					user_sku_15days_browse_cnt   /user_sku_15days_browse_day_cnt    as user_sku_15days_day_avg_browse_cnt  ,
					user_sku_15days_add_cart_cnt /user_sku_15days_add_cart_day_cnt	as user_sku_15days_day_avg_add_cart_cnt,		
					user_sku_15days_del_cart_cnt /user_sku_15days_del_cart_day_cnt	as user_sku_15days_day_avg_del_cart_cnt,		
					user_sku_15days_order_cnt	 /user_sku_15days_order_day_cnt		as user_sku_15days_day_avg_order_cnt	  ,
					user_sku_15days_focus_cnt	 /user_sku_15days_focus_day_cnt		as user_sku_15days_day_avg_focus_cnt	  ,
					user_sku_15days_click_cnt	 /user_sku_15days_click_day_cnt     as user_sku_15days_day_avg_click_cnt,
					
					user_sku_10days_browse_cnt   /user_sku_10days_browse_day_cnt    as user_sku_10days_day_avg_browse_cnt  ,
					user_sku_10days_add_cart_cnt /user_sku_10days_add_cart_day_cnt	as user_sku_10days_day_avg_add_cart_cnt,		
					user_sku_10days_del_cart_cnt /user_sku_10days_del_cart_day_cnt	as user_sku_10days_day_avg_del_cart_cnt,		
					user_sku_10days_order_cnt	 /user_sku_10days_order_day_cnt		as user_sku_10days_day_avg_order_cnt	  ,
					user_sku_10days_focus_cnt	 /user_sku_10days_focus_day_cnt		as user_sku_10days_day_avg_focus_cnt	  ,
					user_sku_10days_click_cnt	 /user_sku_10days_click_day_cnt     as user_sku_10days_day_avg_click_cnt,
					
					user_sku_7days_browse_cnt   /user_sku_7days_browse_day_cnt      as user_sku_7days_day_avg_browse_cnt  ,
					user_sku_7days_add_cart_cnt	/user_sku_7days_add_cart_day_cnt	as user_sku_7days_day_avg_add_cart_cnt,		
					user_sku_7days_del_cart_cnt	/user_sku_7days_del_cart_day_cnt	as user_sku_7days_day_avg_del_cart_cnt,		
					user_sku_7days_order_cnt	/user_sku_7days_order_day_cnt		as user_sku_7days_day_avg_order_cnt	  ,
					user_sku_7days_focus_cnt	/user_sku_7days_focus_day_cnt		as user_sku_7days_day_avg_focus_cnt	  ,
					user_sku_7days_click_cnt	/user_sku_7days_click_day_cnt       as user_sku_7days_day_avg_click_cnt,
					
					user_sku_5days_browse_cnt   /user_sku_5days_browse_day_cnt      as user_sku_5days_day_avg_browse_cnt  ,
					user_sku_5days_add_cart_cnt	/user_sku_5days_add_cart_day_cnt	as user_sku_5days_day_avg_add_cart_cnt,		
					user_sku_5days_del_cart_cnt	/user_sku_5days_del_cart_day_cnt	as user_sku_5days_day_avg_del_cart_cnt,		
					user_sku_5days_order_cnt	/user_sku_5days_order_day_cnt		as user_sku_5days_day_avg_order_cnt	  ,
					user_sku_5days_focus_cnt	/user_sku_5days_focus_day_cnt		as user_sku_5days_day_avg_focus_cnt	  ,
					user_sku_5days_click_cnt	/user_sku_5days_click_day_cnt       as user_sku_5days_day_avg_click_cnt,
					
					user_sku_3days_browse_cnt   /user_sku_3days_browse_day_cnt      as user_sku_3days_day_avg_browse_cnt  ,
					user_sku_3days_add_cart_cnt	/user_sku_3days_add_cart_day_cnt	as user_sku_3days_day_avg_add_cart_cnt,		
					user_sku_3days_del_cart_cnt	/user_sku_3days_del_cart_day_cnt	as user_sku_3days_day_avg_del_cart_cnt,		
					user_sku_3days_order_cnt	/user_sku_3days_order_day_cnt		as user_sku_3days_day_avg_order_cnt	  ,
					user_sku_3days_focus_cnt	/user_sku_3days_focus_day_cnt		as user_sku_3days_day_avg_focus_cnt	  ,
					user_sku_3days_click_cnt	/user_sku_3days_click_day_cnt       as user_sku_3days_day_avg_click_cnt
					
					from dev.dev_temp_msj_risk_jdata_feature_user_sku_dim_v3_${suffix}
            )
            a
    left outer join
            (
                    select *,
					user_month_browse_cnt   /user_month_browse_day_cnt      as user_month_day_avg_browse_cnt  ,
					user_month_add_cart_cnt	/user_month_add_cart_day_cnt	as user_month_day_avg_add_cart_cnt,		
					user_month_del_cart_cnt	/user_month_del_cart_day_cnt	as user_month_day_avg_del_cart_cnt,		
					user_month_order_cnt	/user_month_order_day_cnt		as user_month_day_avg_order_cnt	  ,
					user_month_focus_cnt	/user_month_focus_day_cnt		as user_month_day_avg_focus_cnt	  ,
					user_month_click_cnt	/user_month_click_day_cnt       as user_month_day_avg_click_cnt   ,
					user_month_browse_cnt   /user_month_browse_sku_cnt      as user_month_sku_avg_browse_cnt  ,
					user_month_add_cart_cnt	/user_month_add_cart_sku_cnt	as user_month_sku_avg_add_cart_cnt,		
					user_month_del_cart_cnt	/user_month_del_cart_sku_cnt	as user_month_sku_avg_del_cart_cnt,		
					user_month_order_cnt	/user_month_order_sku_cnt       as user_month_sku_avg_order_cnt	  ,
					user_month_focus_cnt	/user_month_focus_sku_cnt       as user_month_sku_avg_focus_cnt	  ,
					user_month_click_cnt	/user_month_click_sku_cnt       as user_month_sku_avg_click_cnt   ,
					user_month_browse_cnt   /user_month_browse_brand_cnt    as user_month_brand_avg_browse_cnt  ,
					user_month_add_cart_cnt	/user_month_add_cart_brand_cnt	as user_month_brand_avg_add_cart_cnt,		
					user_month_del_cart_cnt	/user_month_del_cart_brand_cnt	as user_month_brand_avg_del_cart_cnt,		
					user_month_order_cnt	/user_month_order_brand_cnt     as user_month_brand_avg_order_cnt	  ,
					user_month_focus_cnt	/user_month_focus_brand_cnt     as user_month_brand_avg_focus_cnt	  ,
					user_month_click_cnt	/user_month_click_brand_cnt     as user_month_brand_avg_click_cnt,
					
					user_15days_browse_cnt   /user_15days_browse_day_cnt      as user_15days_day_avg_browse_cnt  ,
					user_15days_add_cart_cnt /user_15days_add_cart_day_cnt	  as user_15days_day_avg_add_cart_cnt,		
					user_15days_del_cart_cnt /user_15days_del_cart_day_cnt	  as user_15days_day_avg_del_cart_cnt,		
					user_15days_order_cnt	 /user_15days_order_day_cnt		  as user_15days_day_avg_order_cnt	  ,
					user_15days_focus_cnt	 /user_15days_focus_day_cnt		  as user_15days_day_avg_focus_cnt	  ,
					user_15days_click_cnt	 /user_15days_click_day_cnt       as user_15days_day_avg_click_cnt   ,
					user_15days_browse_cnt   /user_15days_browse_sku_cnt      as user_15days_sku_avg_browse_cnt  ,
					user_15days_add_cart_cnt /user_15days_add_cart_sku_cnt	  as user_15days_sku_avg_add_cart_cnt,		
					user_15days_del_cart_cnt /user_15days_del_cart_sku_cnt	  as user_15days_sku_avg_del_cart_cnt,		
					user_15days_order_cnt	 /user_15days_order_sku_cnt       as user_15days_sku_avg_order_cnt	  ,
					user_15days_focus_cnt	 /user_15days_focus_sku_cnt       as user_15days_sku_avg_focus_cnt	  ,
					user_15days_click_cnt	 /user_15days_click_sku_cnt       as user_15days_sku_avg_click_cnt   ,
					user_15days_browse_cnt   /user_15days_browse_brand_cnt    as user_15days_brand_avg_browse_cnt  ,
					user_15days_add_cart_cnt /user_15days_add_cart_brand_cnt  as user_15days_brand_avg_add_cart_cnt,		
					user_15days_del_cart_cnt /user_15days_del_cart_brand_cnt  as user_15days_brand_avg_del_cart_cnt,		
					user_15days_order_cnt	 /user_15days_order_brand_cnt     as user_15days_brand_avg_order_cnt	  ,
					user_15days_focus_cnt	 /user_15days_focus_brand_cnt     as user_15days_brand_avg_focus_cnt	  ,
					user_15days_click_cnt	 /user_15days_click_brand_cnt     as user_15days_brand_avg_click_cnt,
					
					user_10days_browse_cnt   /user_10days_browse_day_cnt      as user_10days_day_avg_browse_cnt  ,
					user_10days_add_cart_cnt /user_10days_add_cart_day_cnt	  as user_10days_day_avg_add_cart_cnt,		
					user_10days_del_cart_cnt /user_10days_del_cart_day_cnt	  as user_10days_day_avg_del_cart_cnt,		
					user_10days_order_cnt	 /user_10days_order_day_cnt		  as user_10days_day_avg_order_cnt	  ,
					user_10days_focus_cnt	 /user_10days_focus_day_cnt		  as user_10days_day_avg_focus_cnt	  ,
					user_10days_click_cnt	 /user_10days_click_day_cnt       as user_10days_day_avg_click_cnt   ,
					user_10days_browse_cnt   /user_10days_browse_sku_cnt      as user_10days_sku_avg_browse_cnt  ,
					user_10days_add_cart_cnt /user_10days_add_cart_sku_cnt	  as user_10days_sku_avg_add_cart_cnt,		
					user_10days_del_cart_cnt /user_10days_del_cart_sku_cnt	  as user_10days_sku_avg_del_cart_cnt,		
					user_10days_order_cnt	 /user_10days_order_sku_cnt       as user_10days_sku_avg_order_cnt	  ,
					user_10days_focus_cnt	 /user_10days_focus_sku_cnt       as user_10days_sku_avg_focus_cnt	  ,
					user_10days_click_cnt	 /user_10days_click_sku_cnt       as user_10days_sku_avg_click_cnt   ,
					user_10days_browse_cnt   /user_10days_browse_brand_cnt    as user_10days_brand_avg_browse_cnt  ,
					user_10days_add_cart_cnt /user_10days_add_cart_brand_cnt  as user_10days_brand_avg_add_cart_cnt,		
					user_10days_del_cart_cnt /user_10days_del_cart_brand_cnt  as user_10days_brand_avg_del_cart_cnt,		
					user_10days_order_cnt	 /user_10days_order_brand_cnt     as user_10days_brand_avg_order_cnt	  ,
					user_10days_focus_cnt	 /user_10days_focus_brand_cnt     as user_10days_brand_avg_focus_cnt	  ,
					user_10days_click_cnt	 /user_10days_click_brand_cnt     as user_10days_brand_avg_click_cnt,
					
					user_7days_browse_cnt   /user_7days_browse_day_cnt      as user_7days_day_avg_browse_cnt  ,
					user_7days_add_cart_cnt	/user_7days_add_cart_day_cnt	as user_7days_day_avg_add_cart_cnt,		
					user_7days_del_cart_cnt	/user_7days_del_cart_day_cnt	as user_7days_day_avg_del_cart_cnt,		
					user_7days_order_cnt	/user_7days_order_day_cnt		as user_7days_day_avg_order_cnt	  ,
					user_7days_focus_cnt	/user_7days_focus_day_cnt		as user_7days_day_avg_focus_cnt	  ,
					user_7days_click_cnt	/user_7days_click_day_cnt       as user_7days_day_avg_click_cnt   ,
					user_7days_browse_cnt   /user_7days_browse_sku_cnt      as user_7days_sku_avg_browse_cnt  ,
					user_7days_add_cart_cnt	/user_7days_add_cart_sku_cnt	as user_7days_sku_avg_add_cart_cnt,		
					user_7days_del_cart_cnt	/user_7days_del_cart_sku_cnt	as user_7days_sku_avg_del_cart_cnt,		
					user_7days_order_cnt	/user_7days_order_sku_cnt       as user_7days_sku_avg_order_cnt	  ,
					user_7days_focus_cnt	/user_7days_focus_sku_cnt       as user_7days_sku_avg_focus_cnt	  ,
					user_7days_click_cnt	/user_7days_click_sku_cnt       as user_7days_sku_avg_click_cnt   ,
					user_7days_browse_cnt   /user_7days_browse_brand_cnt    as user_7days_brand_avg_browse_cnt  ,
					user_7days_add_cart_cnt	/user_7days_add_cart_brand_cnt	as user_7days_brand_avg_add_cart_cnt,		
					user_7days_del_cart_cnt	/user_7days_del_cart_brand_cnt	as user_7days_brand_avg_del_cart_cnt,		
					user_7days_order_cnt	/user_7days_order_brand_cnt     as user_7days_brand_avg_order_cnt	  ,
					user_7days_focus_cnt	/user_7days_focus_brand_cnt     as user_7days_brand_avg_focus_cnt	  ,
					user_7days_click_cnt	/user_7days_click_brand_cnt     as user_7days_brand_avg_click_cnt,
					
					
					user_5days_browse_cnt   /user_5days_browse_day_cnt      as user_5days_day_avg_browse_cnt  ,
					user_5days_add_cart_cnt	/user_5days_add_cart_day_cnt	as user_5days_day_avg_add_cart_cnt,		
					user_5days_del_cart_cnt	/user_5days_del_cart_day_cnt	as user_5days_day_avg_del_cart_cnt,		
					user_5days_order_cnt	/user_5days_order_day_cnt		as user_5days_day_avg_order_cnt	  ,
					user_5days_focus_cnt	/user_5days_focus_day_cnt		as user_5days_day_avg_focus_cnt	  ,
					user_5days_click_cnt	/user_5days_click_day_cnt       as user_5days_day_avg_click_cnt   ,
					user_5days_browse_cnt   /user_5days_browse_sku_cnt      as user_5days_sku_avg_browse_cnt  ,
					user_5days_add_cart_cnt	/user_5days_add_cart_sku_cnt	as user_5days_sku_avg_add_cart_cnt,		
					user_5days_del_cart_cnt	/user_5days_del_cart_sku_cnt	as user_5days_sku_avg_del_cart_cnt,		
					user_5days_order_cnt	/user_5days_order_sku_cnt       as user_5days_sku_avg_order_cnt	  ,
					user_5days_focus_cnt	/user_5days_focus_sku_cnt       as user_5days_sku_avg_focus_cnt	  ,
					user_5days_click_cnt	/user_5days_click_sku_cnt       as user_5days_sku_avg_click_cnt   ,
					user_5days_browse_cnt   /user_5days_browse_brand_cnt    as user_5days_brand_avg_browse_cnt  ,
					user_5days_add_cart_cnt	/user_5days_add_cart_brand_cnt	as user_5days_brand_avg_add_cart_cnt,		
					user_5days_del_cart_cnt	/user_5days_del_cart_brand_cnt	as user_5days_brand_avg_del_cart_cnt,		
					user_5days_order_cnt	/user_5days_order_brand_cnt     as user_5days_brand_avg_order_cnt	  ,
					user_5days_focus_cnt	/user_5days_focus_brand_cnt     as user_5days_brand_avg_focus_cnt	  ,
					user_5days_click_cnt	/user_5days_click_brand_cnt     as user_5days_brand_avg_click_cnt,
					
					user_3days_browse_cnt   /user_3days_browse_day_cnt      as user_3days_day_avg_browse_cnt  ,
					user_3days_add_cart_cnt	/user_3days_add_cart_day_cnt	as user_3days_day_avg_add_cart_cnt,		
					user_3days_del_cart_cnt	/user_3days_del_cart_day_cnt	as user_3days_day_avg_del_cart_cnt,		
					user_3days_order_cnt	/user_3days_order_day_cnt		as user_3days_day_avg_order_cnt	  ,
					user_3days_focus_cnt	/user_3days_focus_day_cnt		as user_3days_day_avg_focus_cnt	  ,
					user_3days_click_cnt	/user_3days_click_day_cnt       as user_3days_day_avg_click_cnt   ,
					user_3days_browse_cnt   /user_3days_browse_sku_cnt      as user_3days_sku_avg_browse_cnt  ,
					user_3days_add_cart_cnt	/user_3days_add_cart_sku_cnt	as user_3days_sku_avg_add_cart_cnt,		
					user_3days_del_cart_cnt	/user_3days_del_cart_sku_cnt	as user_3days_sku_avg_del_cart_cnt,		
					user_3days_order_cnt	/user_3days_order_sku_cnt       as user_3days_sku_avg_order_cnt	  ,
					user_3days_focus_cnt	/user_3days_focus_sku_cnt       as user_3days_sku_avg_focus_cnt	  ,
					user_3days_click_cnt	/user_3days_click_sku_cnt       as user_3days_sku_avg_click_cnt   ,
					user_3days_browse_cnt   /user_3days_browse_brand_cnt    as user_3days_brand_avg_browse_cnt  ,
					user_3days_add_cart_cnt	/user_3days_add_cart_brand_cnt	as user_3days_brand_avg_add_cart_cnt,		
					user_3days_del_cart_cnt	/user_3days_del_cart_brand_cnt	as user_3days_brand_avg_del_cart_cnt,		
					user_3days_order_cnt	/user_3days_order_brand_cnt     as user_3days_brand_avg_order_cnt	  ,
					user_3days_focus_cnt	/user_3days_focus_brand_cnt     as user_3days_brand_avg_focus_cnt	  ,
					user_3days_click_cnt	/user_3days_click_brand_cnt     as user_3days_brand_avg_click_cnt

					from dev.dev_temp_msj_risk_jdata_feature_user_dim_v3_${suffix}
            )
            b
    on
            a.user_id = b.user_id
    left outer join
            (
                    select *, 
					(coalesce(sku_month_click_cnt,0)*0.01+coalesce(sku_month_order_cnt,0)*0.5+coalesce(sku_month_add_cart_cnt,0)*0.1-coalesce(sku_month_del_cart_cnt,0)*0.1+coalesce(sku_month_focus_cnt,0)*0.1) as sku_month_hot_level,
					(coalesce(sku_15days_click_cnt,0)*0.01+coalesce(sku_15days_order_cnt,0)*0.5+coalesce(sku_15days_add_cart_cnt,0)*0.1-coalesce(sku_15days_del_cart_cnt,0)*0.1+coalesce(sku_15days_focus_cnt,0)*0.1) as sku_15days_hot_level, 
					(coalesce(sku_10days_click_cnt,0)*0.01+coalesce(sku_10days_order_cnt,0)*0.5+coalesce(sku_10days_add_cart_cnt,0)*0.1-coalesce(sku_10days_del_cart_cnt,0)*0.1+coalesce(sku_10days_focus_cnt,0)*0.1) as sku_10days_hot_level, 
					(coalesce(sku_7days_click_cnt,0)*0.01+coalesce(sku_7days_order_cnt,0)*0.5+coalesce(sku_7days_add_cart_cnt,0)*0.1-coalesce(sku_7days_del_cart_cnt,0)*0.1+coalesce(sku_7days_focus_cnt,0)*0.1) as sku_7days_hot_level, 
					(coalesce(sku_5days_click_cnt,0)*0.01+coalesce(sku_5days_order_cnt,0)*0.5+coalesce(sku_5days_add_cart_cnt,0)*0.1-coalesce(sku_5days_del_cart_cnt,0)*0.1+coalesce(sku_5days_focus_cnt,0)*0.1) as sku_5days_hot_level, 
					(coalesce(sku_3days_click_cnt,0)*0.01+coalesce(sku_3days_order_cnt,0)*0.5+coalesce(sku_3days_add_cart_cnt,0)*0.1-coalesce(sku_3days_del_cart_cnt,0)*0.1+coalesce(sku_3days_focus_cnt,0)*0.1) as sku_3days_hot_level,
					(coalesce(sku_1days_click_cnt,0)*0.01+coalesce(sku_1days_order_cnt,0)*0.5+coalesce(sku_1days_add_cart_cnt,0)*0.1-coalesce(sku_1days_del_cart_cnt,0)*0.1+coalesce(sku_1days_focus_cnt,0)*0.1) as sku_1days_hot_level
					from dev.dev_temp_msj_risk_jdata_feature_sku_dim_v3_${suffix}
            )
            c
    on
            a.sku_id = c.sku_id
	left outer join
            (
                    select * ,
					(coalesce(brand_month_click_cnt,0)*0.01+coalesce(brand_month_order_cnt,0)*0.5+coalesce(brand_month_add_cart_cnt,0)*0.1-coalesce(brand_month_del_cart_cnt,0)*0.1+coalesce(brand_month_focus_cnt,0)*0.1) as brand_month_hot_level,
					(coalesce(brand_15days_click_cnt,0)*0.01+coalesce(brand_15days_order_cnt,0)*0.5+coalesce(brand_15days_add_cart_cnt,0)*0.1-coalesce(brand_15days_del_cart_cnt,0)*0.1+coalesce(brand_15days_focus_cnt,0)*0.1) as brand_15days_hot_level, 
					(coalesce(brand_10days_click_cnt,0)*0.01+coalesce(brand_10days_order_cnt,0)*0.5+coalesce(brand_10days_add_cart_cnt,0)*0.1-coalesce(brand_10days_del_cart_cnt,0)*0.1+coalesce(brand_10days_focus_cnt,0)*0.1) as brand_10days_hot_level, 
					(coalesce(brand_7days_click_cnt,0)*0.01+coalesce(brand_7days_order_cnt,0)*0.5+coalesce(brand_7days_add_cart_cnt,0)*0.1-coalesce(brand_7days_del_cart_cnt,0)*0.1+coalesce(brand_7days_focus_cnt,0)*0.1) as brand_7days_hot_level, 
					(coalesce(brand_5days_click_cnt,0)*0.01+coalesce(brand_5days_order_cnt,0)*0.5+coalesce(brand_5days_add_cart_cnt,0)*0.1-coalesce(brand_5days_del_cart_cnt,0)*0.1+coalesce(brand_5days_focus_cnt,0)*0.1) as brand_5days_hot_level, 
					(coalesce(brand_3days_click_cnt,0)*0.01+coalesce(brand_3days_order_cnt,0)*0.5+coalesce(brand_3days_add_cart_cnt,0)*0.1-coalesce(brand_3days_del_cart_cnt,0)*0.1+coalesce(brand_3days_focus_cnt,0)*0.1) as brand_3days_hot_level,
					(coalesce(brand_1days_click_cnt,0)*0.01+coalesce(brand_1days_order_cnt,0)*0.5+coalesce(brand_1days_add_cart_cnt,0)*0.1-coalesce(brand_1days_del_cart_cnt,0)*0.1+coalesce(brand_1days_focus_cnt,0)*0.1) as brand_1days_hot_level
					
					from dev.dev_temp_msj_risk_jdata_feature_brand_dim_v3_${suffix}
            )
            d
    on
            a.action_brand = d.action_brand
	left outer join
	(
                    select *,
					user_brand_month_browse_cnt     /user_brand_month_browse_day_cnt      as user_brand_month_day_avg_browse_cnt  ,
					user_brand_month_add_cart_cnt	/user_brand_month_add_cart_day_cnt	  as user_brand_month_day_avg_add_cart_cnt,		
					user_brand_month_del_cart_cnt	/user_brand_month_del_cart_day_cnt	  as user_brand_month_day_avg_del_cart_cnt,		
					user_brand_month_order_cnt	    /user_brand_month_order_day_cnt		  as user_brand_month_day_avg_order_cnt	  ,
					user_brand_month_focus_cnt	    /user_brand_month_focus_day_cnt		  as user_brand_month_day_avg_focus_cnt	  ,
					user_brand_month_click_cnt	    /user_brand_month_click_day_cnt       as user_brand_month_day_avg_click_cnt,
					
					user_brand_15days_browse_cnt   /user_brand_15days_browse_day_cnt    as user_brand_15days_day_avg_browse_cnt  ,
					user_brand_15days_add_cart_cnt /user_brand_15days_add_cart_day_cnt	as user_brand_15days_day_avg_add_cart_cnt,		
					user_brand_15days_del_cart_cnt /user_brand_15days_del_cart_day_cnt	as user_brand_15days_day_avg_del_cart_cnt,		
					user_brand_15days_order_cnt	   /user_brand_15days_order_day_cnt		as user_brand_15days_day_avg_order_cnt	  ,
					user_brand_15days_focus_cnt	   /user_brand_15days_focus_day_cnt		as user_brand_15days_day_avg_focus_cnt	  ,
					user_brand_15days_click_cnt	   /user_brand_15days_click_day_cnt     as user_brand_15days_day_avg_click_cnt,
					
					user_brand_10days_browse_cnt   /user_brand_10days_browse_day_cnt    as user_brand_10days_day_avg_browse_cnt  ,
					user_brand_10days_add_cart_cnt /user_brand_10days_add_cart_day_cnt	as user_brand_10days_day_avg_add_cart_cnt,		
					user_brand_10days_del_cart_cnt /user_brand_10days_del_cart_day_cnt	as user_brand_10days_day_avg_del_cart_cnt,		
					user_brand_10days_order_cnt	   /user_brand_10days_order_day_cnt		as user_brand_10days_day_avg_order_cnt	  ,
					user_brand_10days_focus_cnt	   /user_brand_10days_focus_day_cnt		as user_brand_10days_day_avg_focus_cnt	  ,
					user_brand_10days_click_cnt	   /user_brand_10days_click_day_cnt     as user_brand_10days_day_avg_click_cnt,
					
					user_brand_7days_browse_cnt   /user_brand_7days_browse_day_cnt      as user_brand_7days_day_avg_browse_cnt  ,
					user_brand_7days_add_cart_cnt /user_brand_7days_add_cart_day_cnt	as user_brand_7days_day_avg_add_cart_cnt,		
					user_brand_7days_del_cart_cnt /user_brand_7days_del_cart_day_cnt	as user_brand_7days_day_avg_del_cart_cnt,		
					user_brand_7days_order_cnt	  /user_brand_7days_order_day_cnt		as user_brand_7days_day_avg_order_cnt	  ,
					user_brand_7days_focus_cnt	  /user_brand_7days_focus_day_cnt		as user_brand_7days_day_avg_focus_cnt	  ,
					user_brand_7days_click_cnt	  /user_brand_7days_click_day_cnt       as user_brand_7days_day_avg_click_cnt,
					
					user_brand_5days_browse_cnt   /user_brand_5days_browse_day_cnt      as user_brand_5days_day_avg_browse_cnt  ,
					user_brand_5days_add_cart_cnt /user_brand_5days_add_cart_day_cnt	as user_brand_5days_day_avg_add_cart_cnt,		
					user_brand_5days_del_cart_cnt /user_brand_5days_del_cart_day_cnt	as user_brand_5days_day_avg_del_cart_cnt,		
					user_brand_5days_order_cnt	  /user_brand_5days_order_day_cnt		as user_brand_5days_day_avg_order_cnt	  ,
					user_brand_5days_focus_cnt	  /user_brand_5days_focus_day_cnt		as user_brand_5days_day_avg_focus_cnt	  ,
					user_brand_5days_click_cnt	  /user_brand_5days_click_day_cnt       as user_brand_5days_day_avg_click_cnt,
					
					user_brand_3days_browse_cnt   /user_brand_3days_browse_day_cnt      as user_brand_3days_day_avg_browse_cnt  ,
					user_brand_3days_add_cart_cnt /user_brand_3days_add_cart_day_cnt	as user_brand_3days_day_avg_add_cart_cnt,		
					user_brand_3days_del_cart_cnt /user_brand_3days_del_cart_day_cnt	as user_brand_3days_day_avg_del_cart_cnt,		
					user_brand_3days_order_cnt	  /user_brand_3days_order_day_cnt		as user_brand_3days_day_avg_order_cnt	  ,
					user_brand_3days_focus_cnt	  /user_brand_3days_focus_day_cnt		as user_brand_3days_day_avg_focus_cnt	  ,
					user_brand_3days_click_cnt	  /user_brand_3days_click_day_cnt       as user_brand_3days_day_avg_click_cnt
					
					from dev.dev_temp_msj_risk_jdata_feature_user_brand_dim_v3_${suffix}
    )e
	on
        a.user_id = e.user_id and a.action_brand = e.action_brand